from email.mime.text import MIMEText
from django.shortcuts import render
from django.http import  JsonResponse
import smtplib

from .models import ReachUp
from . import config
# Create your views here.

def index(request):
    if request.method == "POST":
        name = request.POST["name"]
        email = request.POST["email"]
        subject = request.POST["subject"]
        message = request.POST['message']
        try:
            ReachUp.objects.create(name=name, email=email, subject=subject, message=message)
            converTime ={
                "name":name,
                "message":"Thank you For your Query kindly we will get back to you"
            }
            #AutomateEmail(email, name)
            return JsonResponse(converTime, status=200)
        except:
            print("error")
    else:
        return render(request, "collegeInfo/index.html")


def department(request):
    return render(request,"collegeInfo/departments.html")

def gallery(request):
    return render(request, "collegeInfo/gallery.html")


#---------------email sending part-------------------------------
def AutomateEmail(email,name):
    msg = MIMEText(f"Dear {name}\n\nThank you for your Query we will get back to you soon\n\n This is an autogenerated mail dont replay it")
    msg['Subject'] = config.subject
    msg['From'] = config.sender_mail
    msg['To'] = email
    server =smtplib.SMTP(config.server_address, config.port)
    server.starttls()
    server.login(config.sender_mail, config.password)
    server.sendmail(config.sender_mail, email, msg.as_string())
    print("Mail Sent")
    server.close()