# Generated by Django 4.0.5 on 2022-06-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reachup',
            name='message',
            field=models.CharField(default='hello', max_length=300),
        ),
        migrations.AlterField(
            model_name='reachup',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
