# Generated by Django 4.0.5 on 2022-06-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeInfo', '0002_reachup_message_alter_reachup_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reachup',
            name='message',
            field=models.CharField(default='test message', max_length=300),
        ),
    ]
