# Generated by Django 4.0.5 on 2022-06-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeInfo', '0003_alter_reachup_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reachup',
            name='message',
            field=models.CharField(max_length=300),
        ),
    ]
